experiment_name: clam_uni2h_binary
task: binary
label_column: cancer_label
input_dim: 1536
encoder_name: MahmoodLab/UNI2-h
encoder_family: UNI2-h

embeddings_root: /content/drive/MyDrive/PANDA_PROSTATE/outputs/abmil_uni2h_binary/embeddings
output_root: /content/drive/MyDrive/PANDA_PROSTATE/outputs/clam_uni2h_binary
checkpoints_dir: /content/drive/MyDrive/PANDA_PROSTATE/outputs/clam_uni2h_binary/checkpoints
metrics_dir: /content/drive/MyDrive/PANDA_PROSTATE/outputs/clam_uni2h_binary/metrics
plots_dir: /content/drive/MyDrive/PANDA_PROSTATE/outputs/clam_uni2h_binary/plots

hidden_dim: 256
attention_dim: 128
dropout: 0.25
k_sample: 8
instance_loss_weight: 0.3
epochs: 50
batch_size: 1
learning_rate: 0.0001
weight_decay: 0.00001
early_stopping_patience: 10
monitor: valid_auc
random_seed: 42
threshold_default: 0.5
threshold_selection: Youden
num_workers: 0
pin_memory: false
save_epoch_checkpoints: true
resume: true
mixed_precision: false
device: cuda

max_train: null
max_valid: null
max_test: null
