"""Quality control for PANDA advanced tile extraction ZIP batches.

This script validates ZIP files generated by scripts/41_extract_tiles_advanced_batch.py
without extracting PNG tiles to disk. It inspects ZIP structure, manifests,
summary metadata, tile file presence, tissue thresholds, and per-slide tile
counts, then writes reproducible CSV, JSON, and TXT quality reports.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import statistics
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List

import pandas as pd

BATCH_NAME_RE = re.compile(r"^(batch_(\d{4})_(\d{4}))\.zip$")
DEFAULT_PATTERN = "batch_*.zip"

REQUIRED_INTERNAL_FILES = [
    "summary.json",
    "metadata/tile_manifest.csv",
    "metadata/candidate_tiles_manifest.csv",
    "metadata/checksums.csv",
    "metadata/config_used.yaml",
    "logs/41_extract_tiles_advanced_batch.log",
]

REQUIRED_TILE_COLUMNS = [
    "slide_id",
    "tile_id",
    "tile_path",
    "tissue_pct",
    "mask_pct",
    "selected",
    "selection_rank",
    "split",
    "cancer_label",
    "isup_grade",
    "severity_4_label",
    "gleason_score",
]

REQUIRED_CANDIDATE_COLUMNS = [
    "slide_id",
    "tile_id",
    "tissue_pct",
    "selected",
]

REPORT_COLUMNS = [
    "batch_name",
    "zip_path",
    "zip_size_mb",
    "status",
    "errors_count",
    "warnings_count",
    "slides_processed",
    "slides_failed",
    "total_selected",
    "total_candidates",
    "slides_with_partial_bags",
    "min_selected_per_slide",
    "mean_selected_per_slide",
    "max_selected_per_slide",
    "selected_png_count",
    "manifest_rows",
    "candidate_rows",
    "checksum_rows",
    "low_tissue_selected_count",
    "missing_tile_files_count",
    "duplicate_tile_id_count",
    "duplicate_slide_tile_count",
    "validation_errors",
    "validation_warnings",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate advanced PANDA tile extraction ZIP batches."
    )
    parser.add_argument("--zips-dir", type=Path, required=True)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("quality_reports") / "advanced_tiles_zip_validation",
    )
    parser.add_argument("--expected-batch-size", type=int, default=100)
    parser.add_argument("--expected-total-slides", type=int, default=None)
    parser.add_argument("--tiles-per-slide", type=int, default=128)
    parser.add_argument("--absolute-min-tissue-pct", type=float, default=0.30)
    parser.add_argument("--fail-on-error", action="store_true")
    parser.add_argument("--max-zips", type=int, default=None)
    parser.add_argument("--pattern", default=DEFAULT_PATTERN)
    return parser.parse_args()


def find_zip_files(zips_dir: Path, pattern: str, max_zips: int | None = None) -> list[Path]:
    if not zips_dir.is_dir():
        raise FileNotFoundError(f"No existe --zips-dir: {zips_dir}")
    files = sorted(zips_dir.glob(pattern))
    if max_zips is not None:
        if int(max_zips) < 1:
            raise ValueError("--max-zips debe ser None o un entero >= 1.")
        files = files[: int(max_zips)]
    return files


def parse_batch_name(zip_path: Path) -> dict[str, Any]:
    match = BATCH_NAME_RE.match(zip_path.name)
    if not match:
        return {
            "valid": False,
            "batch_name": zip_path.stem,
            "start": None,
            "end": None,
            "expected_count_from_name": None,
        }
    start = int(match.group(2))
    end = int(match.group(3))
    return {
        "valid": True,
        "batch_name": match.group(1),
        "start": start,
        "end": end,
        "expected_count_from_name": (end - start + 1),
    }


def build_expected_batch_names(expected_total_slides: int, expected_batch_size: int) -> list[str]:
    if int(expected_total_slides) < 1:
        raise ValueError("--expected-total-slides debe ser >= 1 cuando se informa.")
    if int(expected_batch_size) < 1:
        raise ValueError("--expected-batch-size debe ser >= 1.")
    total_batches = int(math.ceil(int(expected_total_slides) / int(expected_batch_size)))
    names = []
    for batch_index in range(total_batches):
        start = batch_index * int(expected_batch_size)
        end = min(start + int(expected_batch_size) - 1, int(expected_total_slides) - 1)
        names.append(f"batch_{start:04d}_{end:04d}")
    return names


def missing_result(batch_name: str, zips_dir: Path) -> dict[str, Any]:
    return {
        "batch_name": batch_name,
        "zip_path": str(zips_dir / f"{batch_name}.zip"),
        "zip_size_mb": 0.0,
        "status": "MISSING",
        "errors_count": 0,
        "warnings_count": 0,
        "slides_processed": 0,
        "slides_failed": 0,
        "total_selected": 0,
        "total_candidates": 0,
        "slides_with_partial_bags": 0,
        "min_selected_per_slide": 0,
        "mean_selected_per_slide": 0.0,
        "max_selected_per_slide": 0,
        "selected_png_count": 0,
        "manifest_rows": 0,
        "candidate_rows": 0,
        "checksum_rows": 0,
        "low_tissue_selected_count": 0,
        "missing_tile_files_count": 0,
        "duplicate_tile_id_count": 0,
        "duplicate_slide_tile_count": 0,
        "validation_errors": "",
        "validation_warnings": "ZIP pendiente/no encontrado en zips_dir",
    }


def normalize_zip_member(path: str) -> str:
    return str(path).replace("\\", "/").lstrip("./")


def normalize_tile_path_from_manifest(tile_path: Any, batch_root: str) -> str:
    """Normalize absolute/relative tile_path into the expected ZIP member path."""
    text = normalize_zip_member(str(tile_path))
    marker = "selected_tiles/"
    if marker not in text:
        return text
    suffix = text.split(marker, 1)[1]
    return f"{batch_root}/{marker}{suffix}".replace("//", "/")


def read_json_from_zip(zf: zipfile.ZipFile, member: str) -> dict[str, Any]:
    with zf.open(member) as file:
        data = json.load(file)
    if not isinstance(data, dict):
        raise ValueError(f"{member} no contiene un objeto JSON.")
    return data


def read_csv_from_zip(zf: zipfile.ZipFile, member: str) -> pd.DataFrame:
    with zf.open(member) as file:
        return pd.read_csv(file, low_memory=False)


def safe_int(value: Any, default: int = 0) -> int:
    if value is None:
        return default
    try:
        if pd.isna(value):
            return default
    except TypeError:
        pass
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def safe_float(value: Any, default: float = 0.0) -> float:
    if value is None:
        return default
    try:
        if pd.isna(value):
            return default
    except TypeError:
        pass
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def validate_required_columns(
    df: pd.DataFrame,
    required_columns: Iterable[str],
    manifest_name: str,
    errors: list[str],
) -> None:
    missing = [column for column in required_columns if column not in df.columns]
    if missing:
        errors.append(f"{manifest_name} missing columns: {missing}")


def collect_png_members(names: set[str], batch_root: str) -> set[str]:
    prefix = f"{batch_root}/selected_tiles/"
    return {
        name
        for name in names
        if name.startswith(prefix) and name.lower().endswith(".png")
    }


def validate_checksums_columns(checksums_df: pd.DataFrame, errors: list[str], warnings: list[str]) -> None:
    lower_to_original = {str(column).lower(): str(column) for column in checksums_df.columns}
    path_columns = {"filename", "tile_path", "path", "file_path"}
    checksum_columns = {"sha256", "checksum", "hash"}
    has_path = bool(path_columns.intersection(lower_to_original.keys()))
    has_checksum = bool(checksum_columns.intersection(lower_to_original.keys()))
    if not has_path:
        errors.append("checksums.csv missing filename/tile_path/path column")
    if not has_checksum:
        warnings.append("checksums.csv missing sha256/checksum/hash column")


def empty_result(zip_path: Path, batch_name: str, errors: list[str], warnings: list[str]) -> dict[str, Any]:
    status = "ERROR" if errors else ("WARNING" if warnings else "OK")
    return {
        "batch_name": batch_name,
        "zip_path": str(zip_path),
        "zip_size_mb": round(zip_path.stat().st_size / (1024 * 1024), 3) if zip_path.exists() else 0.0,
        "status": status,
        "errors_count": len(errors),
        "warnings_count": len(warnings),
        "slides_processed": 0,
        "slides_failed": 0,
        "total_selected": 0,
        "total_candidates": 0,
        "slides_with_partial_bags": 0,
        "min_selected_per_slide": 0,
        "mean_selected_per_slide": 0.0,
        "max_selected_per_slide": 0,
        "selected_png_count": 0,
        "manifest_rows": 0,
        "candidate_rows": 0,
        "checksum_rows": 0,
        "low_tissue_selected_count": 0,
        "missing_tile_files_count": 0,
        "duplicate_tile_id_count": 0,
        "duplicate_slide_tile_count": 0,
        "validation_errors": " | ".join(errors),
        "validation_warnings": " | ".join(warnings),
    }


def validate_single_zip(
    zip_path: Path,
    *,
    expected_batch_size: int,
    tiles_per_slide: int,
    absolute_min_tissue_pct: float,
) -> dict[str, Any]:
    errors: list[str] = []
    warnings: list[str] = []
    parsed = parse_batch_name(zip_path)
    batch_name = str(parsed["batch_name"])

    if not parsed["valid"]:
        errors.append("zip filename does not match batch_0000_0099.zip")
    elif parsed["expected_count_from_name"] != expected_batch_size:
        warnings.append(
            "batch range size from filename "
            f"({parsed['expected_count_from_name']}) != expected_batch_size ({expected_batch_size})"
        )

    try:
        with zipfile.ZipFile(zip_path, "r") as zf:
            bad_file = zf.testzip()
            if bad_file:
                errors.append(f"zip CRC check failed at member: {bad_file}")

            names = {normalize_zip_member(name) for name in zf.namelist()}
            batch_root = batch_name
            root_prefix = f"{batch_root}/"
            if not any(name.startswith(root_prefix) for name in names):
                errors.append(f"missing root folder inside ZIP: {batch_root}/")

            required_members = [f"{batch_root}/{member}" for member in REQUIRED_INTERNAL_FILES]
            for member in required_members:
                if member not in names:
                    errors.append(f"missing required ZIP member: {member}")

            if errors:
                return empty_result(zip_path, batch_name, errors, warnings)

            summary_member = f"{batch_root}/summary.json"
            tile_manifest_member = f"{batch_root}/metadata/tile_manifest.csv"
            candidate_manifest_member = f"{batch_root}/metadata/candidate_tiles_manifest.csv"
            checksums_member = f"{batch_root}/metadata/checksums.csv"

            try:
                summary = read_json_from_zip(zf, summary_member)
            except Exception as exc:
                errors.append(f"summary.json parse error: {exc}")
                summary = {}

            try:
                tile_df = read_csv_from_zip(zf, tile_manifest_member)
            except Exception as exc:
                errors.append(f"tile_manifest.csv read error: {exc}")
                tile_df = pd.DataFrame()

            try:
                candidate_df = read_csv_from_zip(zf, candidate_manifest_member)
            except Exception as exc:
                errors.append(f"candidate_tiles_manifest.csv read error: {exc}")
                candidate_df = pd.DataFrame()

            try:
                checksums_df = read_csv_from_zip(zf, checksums_member)
            except Exception as exc:
                errors.append(f"checksums.csv read error: {exc}")
                checksums_df = pd.DataFrame()

            validate_required_columns(tile_df, REQUIRED_TILE_COLUMNS, "tile_manifest.csv", errors)
            validate_required_columns(candidate_df, REQUIRED_CANDIDATE_COLUMNS, "candidate_tiles_manifest.csv", errors)
            if not checksums_df.empty:
                validate_checksums_columns(checksums_df, errors, warnings)
            else:
                warnings.append("checksums.csv is empty")

            png_members = collect_png_members(names, batch_root)
            selected_png_count = len(png_members)
            manifest_rows = len(tile_df)
            candidate_rows = len(candidate_df)
            checksum_rows = len(checksums_df)

            if selected_png_count != manifest_rows:
                errors.append(
                    f"selected PNG count ({selected_png_count}) != tile_manifest rows ({manifest_rows})"
                )

            missing_tile_files_count = 0
            if "tile_path" in tile_df.columns:
                normalized_paths = [
                    normalize_tile_path_from_manifest(path, batch_root)
                    for path in tile_df["tile_path"].fillna("").tolist()
                ]
                missing_tile_files_count = sum(1 for path in normalized_paths if path not in names)
                if missing_tile_files_count:
                    errors.append(f"missing tile files referenced by manifest: {missing_tile_files_count}")

            if "selected" in tile_df.columns and not tile_df.empty:
                selected_values = pd.to_numeric(tile_df["selected"], errors="coerce").fillna(-1).astype(int)
                non_selected_count = int((selected_values != 1).sum())
                if non_selected_count:
                    errors.append(f"tile_manifest contains selected != 1 rows: {non_selected_count}")

            low_tissue_selected_count = 0
            if "tissue_pct" in tile_df.columns and not tile_df.empty:
                tissue_values = pd.to_numeric(tile_df["tissue_pct"], errors="coerce")
                low_tissue_selected_count = int((tissue_values < float(absolute_min_tissue_pct)).sum())
                if low_tissue_selected_count:
                    errors.append(
                        "selected tiles below absolute_min_tissue_pct "
                        f"({absolute_min_tissue_pct}): {low_tissue_selected_count}"
                    )

            max_selected_per_slide = safe_int(summary.get("max_selected_per_slide"), 0)
            min_selected_per_slide = safe_int(summary.get("min_selected_per_slide"), 0)
            mean_selected_per_slide = safe_float(summary.get("mean_selected_per_slide"), 0.0)
            if "slide_id" in tile_df.columns and not tile_df.empty:
                selected_per_slide = tile_df.groupby("slide_id").size()
                too_many_slides = int((selected_per_slide > int(tiles_per_slide)).sum())
                if too_many_slides:
                    errors.append(f"slides with more than tiles_per_slide={tiles_per_slide}: {too_many_slides}")
                min_selected_per_slide = int(selected_per_slide.min())
                mean_selected_per_slide = float(selected_per_slide.mean())
                max_selected_per_slide = int(selected_per_slide.max())

            slides_failed = safe_int(summary.get("slides_failed"), 0)
            if slides_failed != 0:
                errors.append(f"summary slides_failed != 0: {slides_failed}")

            total_selected = safe_int(summary.get("total_selected"), manifest_rows)
            total_candidates = safe_int(summary.get("total_candidates"), candidate_rows)
            slides_processed = safe_int(summary.get("slides_processed"), 0)
            slides_with_partial_bags = safe_int(summary.get("slides_with_partial_bags"), 0)

            if "total_selected" in summary and total_selected != manifest_rows:
                errors.append(
                    f"summary total_selected ({total_selected}) != tile_manifest rows ({manifest_rows})"
                )

            if "slides_processed" in summary and "slide_id" in tile_df.columns:
                unique_slides = int(tile_df["slide_id"].nunique())
                if slides_processed != unique_slides:
                    errors.append(
                        f"summary slides_processed ({slides_processed}) != unique slide_ids ({unique_slides})"
                    )

            if "max_selected_per_slide" in summary and safe_int(summary.get("max_selected_per_slide")) > int(tiles_per_slide):
                errors.append(
                    f"summary max_selected_per_slide ({summary.get('max_selected_per_slide')}) > tiles_per_slide ({tiles_per_slide})"
                )

            duplicate_tile_id_count = 0
            if "tile_id" in tile_df.columns and not tile_df.empty:
                duplicate_tile_id_count = int(tile_df["tile_id"].duplicated().sum())
                if duplicate_tile_id_count:
                    errors.append(f"duplicate tile_id rows: {duplicate_tile_id_count}")

            duplicate_slide_tile_count = 0
            if {"slide_id", "tile_id"}.issubset(tile_df.columns) and not tile_df.empty:
                duplicate_slide_tile_count = int(tile_df[["slide_id", "tile_id"]].duplicated().sum())
                if duplicate_slide_tile_count:
                    errors.append(f"duplicate slide_id+tile_id rows: {duplicate_slide_tile_count}")

            if "slides_requested" in summary and safe_int(summary.get("slides_requested")) != expected_batch_size:
                warnings.append(
                    f"summary slides_requested ({summary.get('slides_requested')}) != expected_batch_size ({expected_batch_size})"
                )

    except zipfile.BadZipFile as exc:
        errors.append(f"BadZipFile: {exc}")
        return empty_result(zip_path, batch_name, errors, warnings)
    except Exception as exc:
        errors.append(f"unexpected validation error: {type(exc).__name__}: {exc}")
        return empty_result(zip_path, batch_name, errors, warnings)

    status = "ERROR" if errors else ("WARNING" if warnings else "OK")
    return {
        "batch_name": batch_name,
        "zip_path": str(zip_path),
        "zip_size_mb": round(zip_path.stat().st_size / (1024 * 1024), 3),
        "status": status,
        "errors_count": len(errors),
        "warnings_count": len(warnings),
        "slides_processed": slides_processed,
        "slides_failed": slides_failed,
        "total_selected": total_selected,
        "total_candidates": total_candidates,
        "slides_with_partial_bags": slides_with_partial_bags,
        "min_selected_per_slide": min_selected_per_slide,
        "mean_selected_per_slide": mean_selected_per_slide,
        "max_selected_per_slide": max_selected_per_slide,
        "selected_png_count": selected_png_count,
        "manifest_rows": manifest_rows,
        "candidate_rows": candidate_rows,
        "checksum_rows": checksum_rows,
        "low_tissue_selected_count": low_tissue_selected_count,
        "missing_tile_files_count": missing_tile_files_count,
        "duplicate_tile_id_count": duplicate_tile_id_count,
        "duplicate_slide_tile_count": duplicate_slide_tile_count,
        "validation_errors": " | ".join(errors),
        "validation_warnings": " | ".join(warnings),
    }


def status_counts(report_df: pd.DataFrame) -> dict[str, int]:
    counts = report_df["status"].value_counts().to_dict() if not report_df.empty else {}
    return {
        "OK": int(counts.get("OK", 0)),
        "WARNING": int(counts.get("WARNING", 0)),
        "ERROR": int(counts.get("ERROR", 0)),
        "MISSING": int(counts.get("MISSING", 0)),
    }


def numeric_sum(report_df: pd.DataFrame, column: str) -> int:
    if report_df.empty or column not in report_df.columns:
        return 0
    return int(pd.to_numeric(report_df[column], errors="coerce").fillna(0).sum())


def numeric_global_stats(report_df: pd.DataFrame) -> dict[str, Any]:
    if report_df.empty:
        return {
            "global_min_selected_per_slide": 0,
            "global_mean_selected_per_slide": 0.0,
            "global_max_selected_per_slide": 0,
        }
    min_values = pd.to_numeric(report_df["min_selected_per_slide"], errors="coerce").dropna()
    mean_values = pd.to_numeric(report_df["mean_selected_per_slide"], errors="coerce").dropna()
    max_values = pd.to_numeric(report_df["max_selected_per_slide"], errors="coerce").dropna()
    return {
        "global_min_selected_per_slide": int(min_values.min()) if not min_values.empty else 0,
        "global_mean_selected_per_slide": float(mean_values.mean()) if not mean_values.empty else 0.0,
        "global_max_selected_per_slide": int(max_values.max()) if not max_values.empty else 0,
    }


def write_reports(
    results: list[dict[str, Any]],
    *,
    zips_dir: Path,
    output_dir: Path,
    total_zips_found: int,
    total_expected_batches: int | None = None,
    missing_batches: list[str] | None = None,
) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    report_df = pd.DataFrame(results)
    for column in REPORT_COLUMNS:
        if column not in report_df.columns:
            report_df[column] = ""
    report_df = report_df[REPORT_COLUMNS]

    counts = status_counts(report_df)
    global_stats = numeric_global_stats(report_df)
    invalid_batches = report_df.loc[report_df["status"] == "ERROR", "batch_name"].tolist()
    warning_batches = report_df.loc[report_df["status"] == "WARNING", "batch_name"].tolist()
    missing_batches = list(missing_batches or [])
    summary = {
        "datetime": datetime.now(timezone.utc).isoformat(),
        "zips_dir": str(zips_dir),
        "output_dir": str(output_dir),
        "total_zips_found": int(total_zips_found),
        "total_expected_batches": total_expected_batches,
        "zips_missing_count": counts["MISSING"],
        "zips_ok": counts["OK"],
        "zips_warning": counts["WARNING"],
        "zips_error": counts["ERROR"],
        "total_slides_processed": numeric_sum(report_df, "slides_processed"),
        "total_tiles_selected": numeric_sum(report_df, "total_selected"),
        "total_candidates": numeric_sum(report_df, "total_candidates"),
        "total_partial_bags": numeric_sum(report_df, "slides_with_partial_bags"),
        **global_stats,
        "invalid_batches": invalid_batches,
        "warning_batches": warning_batches,
        "missing_batches": missing_batches,
    }

    csv_path = output_dir / "advanced_tile_zips_validation_report.csv"
    json_path = output_dir / "advanced_tile_zips_validation_summary.json"
    txt_path = output_dir / "advanced_tile_zips_validation_summary.txt"

    report_df.to_csv(csv_path, index=False)
    with json_path.open("w", encoding="utf-8") as file:
        json.dump(summary, file, ensure_ascii=False, indent=2)
    with txt_path.open("w", encoding="utf-8") as file:
        file.write("Advanced PANDA tile ZIP validation summary\n")
        file.write("=" * 48 + "\n")
        for key, value in summary.items():
            file.write(f"{key}: {value}\n")
        file.write("\nPer-batch status\n")
        file.write("-" * 48 + "\n")
        if report_df.empty:
            file.write("No ZIP files validated.\n")
        else:
            columns = [
                "batch_name",
                "status",
                "slides_processed",
                "total_selected",
                "slides_failed",
                "errors_count",
                "warnings_count",
            ]
            file.write(report_df[columns].to_string(index=False))
            file.write("\n")

    return {"csv": csv_path, "json": json_path, "txt": txt_path}


def print_console_table(
    results: list[dict[str, Any]],
    *,
    zips_found: int,
    expected_batches: int | None,
    missing_batches: list[str],
) -> None:
    counts = status_counts(pd.DataFrame(results))
    print("\nZIP validation counts")
    print(f"- zips_found: {zips_found}")
    print(f"- expected_batches: {expected_batches if expected_batches is not None else 'N/A'}")
    print(f"- missing_batches: {len(missing_batches)}")
    print(f"- zips_ok: {counts['OK']}")
    print(f"- zips_warning: {counts['WARNING']}")
    print(f"- zips_error: {counts['ERROR']}")

    if not results:
        print("No ZIP files found.")
        return
    df = pd.DataFrame(results)
    columns = [
        "batch_name",
        "status",
        "slides_processed",
        "total_selected",
        "slides_failed",
        "errors_count",
        "warnings_count",
    ]
    print("\nZIP validation results")
    print(df[columns].to_string(index=False))


def main() -> None:
    args = parse_args()
    try:
        zip_files = find_zip_files(args.zips_dir, args.pattern, args.max_zips)
        expected_batch_names: list[str] = []
        if args.expected_total_slides is not None:
            expected_batch_names = build_expected_batch_names(
                expected_total_slides=int(args.expected_total_slides),
                expected_batch_size=int(args.expected_batch_size),
            )
    except Exception as exc:
        print(f"[ERROR] Argument error: {type(exc).__name__}: {exc}")
        raise SystemExit(1) from exc

    results: list[dict[str, Any]] = []
    found_batch_names: set[str] = set()
    for zip_path in zip_files:
        print(f"[INFO] Validating {zip_path}")
        result = validate_single_zip(
            zip_path,
            expected_batch_size=int(args.expected_batch_size),
            tiles_per_slide=int(args.tiles_per_slide),
            absolute_min_tissue_pct=float(args.absolute_min_tissue_pct),
        )
        results.append(result)
        parsed = parse_batch_name(zip_path)
        if parsed["valid"]:
            found_batch_names.add(str(parsed["batch_name"]))

    missing_batches = [
        batch_name for batch_name in expected_batch_names if batch_name not in found_batch_names
    ]
    results.extend(missing_result(batch_name, args.zips_dir) for batch_name in missing_batches)

    report_paths = write_reports(
        results,
        zips_dir=args.zips_dir,
        output_dir=args.output_dir,
        total_zips_found=len(zip_files),
        total_expected_batches=len(expected_batch_names) if expected_batch_names else None,
        missing_batches=missing_batches,
    )
    print_console_table(
        results,
        zips_found=len(zip_files),
        expected_batches=len(expected_batch_names) if expected_batch_names else None,
        missing_batches=missing_batches,
    )
    print("\nReports generated:")
    for label, path in report_paths.items():
        print(f"- {label}: {path}")

    has_errors = any(result.get("status") == "ERROR" for result in results)
    if has_errors and args.fail_on_error:
        raise SystemExit(1)
    raise SystemExit(0)


if __name__ == "__main__":
    main()
