data_root: /kaggle/input/competitions/prostate-cancer-grade-assessment
train_csv: /kaggle/input/competitions/prostate-cancer-grade-assessment/train.csv
train_images_dir: /kaggle/input/competitions/prostate-cancer-grade-assessment/train_images
train_label_masks_dir: /kaggle/input/competitions/prostate-cancer-grade-assessment/train_label_masks
test_images_dir: /kaggle/input/competitions/prostate-cancer-grade-assessment/test_images
sample_submission_csv: /kaggle/input/competitions/prostate-cancer-grade-assessment/sample_submission.csv

outputs_dir: /kaggle/working/panda_outputs

tile_size: 256
tile_level: 0
tiles_per_slide: 32
max_slides: 20
min_tissue_pct: 0.50
min_mask_pct: 0.01
max_candidates_per_slide: 4000
random_seed: 42

split:
  train_size: 0.70
  valid_size: 0.15
  test_size: 0.15
  stratify_by: isup_grade
